config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  resources :students



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/student.rb
class Student < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  def index
    @students = Student.all
  end

  def new
    @student = Student.new
  end

  def create
    student = Student.new(student_params)
    if student.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
    
  end

  def show
    @student = Student.find(params[:id])
  end

  def edit
    @student = Student.find(params[:id])
  end

  def update
    student = Student.find(params[:id])
    if student.update(student_params)
      redirect_to :action => "show", :id => student.id
    else
      redirect_to :action => "new"
    end
  end

  def destroy
    student = Student.find(params[:id])
    student.destroy
    redirect_to action: :index
  end

  private
  def student_params
    params.require(:student).permit(:name,:profile,:mentor,:grade)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Geekkobe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<%= form_for @student do |f| %>
   <%= f.text_field :name %>
    <%= f.text_field :profile, :size => 140 %>
     <%= f.text_field :mentor %>
      <%= f.text_field :grade %>
  <%= f.submit "編集する" %>
<% end %>

app/views/students/index.html.erb
<h1>Geek</h1>
<h3>生徒メンター情報一覧</h3>
<%= link_to "新規作成へ", new_student_path %>
<div class="students-container">
  <% @students.each do |t| %>
    <div class="student">
      <%= t.name %>
      <%= t.profile %>
      <%= t.mentor %>
      <%= t.grade %>
      <%= t.created_at %>
      <%= link_to "詳細へ", student_path(t.id) %>
      <%= link_to "編集する", edit_student_path(t.id) %>
      <%= button_to "削除する", student_path(t.id), method: :delete %>
    </div>
  <% end %>
</div>

app/views/students/new.html.erb
<h1>Geek</h1>
<h3>新規情報</h3>
<%= form_for @student do |f| %>
  <div class="field">
    <%= f.text_field :name %>
    <%= f.text_field :profile, :size => 140 %>
     <%= f.text_field :mentor %>
      <%= f.text_field :grade %>
  </div>
  

  <%= f.submit "追加する" %>
<% end %>
<%= link_to "生徒情報一覧に戻る", students_path %>

app/views/students/show.html.erb
<h1>Geek</h1>
<h3>生徒情報詳細</h3>
<div class="student">
  <p><%= @student.name %></p>
  <p><%= @student.profile %></p>
  <p><%= @student.mentor %></p>
  <p><%= @student.grade %></p>
  <p><%= @student.created_at %></p>
</div>

<%= link_to "編集する", edit_student_path(@student.id) %>
<%= link_to "生徒情報一覧に戻る", students_path %>